name: Publish to ghrc.io
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@2
      - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the image
      run: docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
      -name: Push the image
      run:  docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
